# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            'Paul Sheridan'
tagline:          ''
description:      'Engineer, Veteran, Tinkerer, Father of Two Delightful Little Girls'
url:              http://www.paulmsheridan.com/
baseurl:          /

author:
  name:           'Paul Sheridan'
  url:            http://www.paulmsheridan.com/

credit:
  name:           'Mark Otto'
  url:            https://github.com/poole/hyde

paginate:         5

collections:
  projects:
    output: true


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
  profile:        https://github.com/psheridan1979
linkedin:         https://www.linkedin.com/in/paulmatthewsheridan
email:            paul.m.sheridan@gmail.com


# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
